# Setup of the window
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Starting Template"
FPS = 60

PLAYER_SCALING = 2
PLAYER_WIDTH = 38
PLAYER_HEIGHT = 38
BEAT_SCALING = 1
BEAT_WIDTH = 50
BEAT_HEIGHT = 50

# Relating to board/positions of things
LANE_START = 200
LANE_SIZE = 100
NUM_LANES = 5
PERFECT_LINE_Y = 100
PLAYER_START_Y = 40

PLAYER_MOVEMENT_SPEED = 5
BEAT_SPEED = 1

# Relating to scoring
PERFECT_SCORE = 5

# Colours
# In pixels
SQUARE_BEAT_DIMS = 78
